# Generated by Django 3.2.9 on 2021-11-06 19:34

import dastugo_blog_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dastugo_blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='media/default_post_image.png', upload_to=dastugo_blog_app.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Publish'), ('a', 'Archieved')], default='d', max_length=20),
        ),
    ]
