# Generated by Django 3.2.9 on 2021-11-07 13:27

import dastugo_blog_app.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dastugo_blog_app', '0003_comment_like_postview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publish_date']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.AddField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 7, 16, 27, 35, 422681)),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(help_text='Select  category(ies) for this post', to='dastugo_blog_app.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default_post_image.png', upload_to=dastugo_blog_app.models.user_directory_path),
        ),
    ]
