# Generated by Django 3.2.9 on 2021-11-07 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dastugo_blog_app', '0004_auto_20211107_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 7, 18, 27, 58, 676118)),
        ),
    ]
