# Generated by Django 3.2.9 on 2021-11-07 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dastugo_blog_app', '0005_alter_post_publish_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='liker',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 7, 19, 27, 30, 423035)),
        ),
    ]
