# Generated by Django 3.2.9 on 2021-11-07 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dastugo_blog_app', '0006_auto_20211107_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 7, 21, 15, 10, 673249)),
        ),
    ]
