# Generated by Django 3.2.9 on 2021-11-19 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dastugo_blog_app', '0009_auto_20211119_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 19, 12, 49, 12, 193837)),
        ),
    ]
